### PR TITLE
Hetero beams support

### PR DESCRIPTION
**Pull request by bennahugo**
Still a draft - lots of debugging ahead, but this is the basic idea

At the moment only doing pybeams_fits, however inside TurboSim
it seems both pybeam_fits and @twillis449 fits_beams0 are available. I'm not really sure what the difference is.
https://github.com/ratt-ru/meqtrees-cattery/blob/f4788bacd67afbc75b833aecc3537e1f1e4fcdbf/Cattery/Siamese/turbo-sim.py#L111-L112
and inside stefcal it looks like only pybeams_fits is available as an option

Please advise if I need to modify both... @o-smirnov seems to think fits_beams0 is abandonware???

For context this ports the recently developed heterogeneous beams support from DDFacet / killMS into the cattery so that we can get simulation capability for SKA-MID
See: https://github.com/cyriltasse/DDFacet/pull/812

### CODE REVIEW

**Comment by bennahugo** [comment]
I'm also changing the behaviour to select the beamset with the closest overlapping frequency coverage. Current behaviour is to only take a single beamset. This change will give us similar behaviour to DDFacet where the beamset with the closest coverage will be picked.

Note that there is some code here
https://github.com/ratt-ru/meqtrees-cattery/blob/4ee7d53b6ce1c6ec37b7144de2f5948fbe59b762/Cattery/Siamese/OMS/InterpolatedBeams.py#L365
that will seemingly interpolate between different sets, but it is unused as far as I can tell??? @o-smirnov please clarify whether you are happy to have the behaviour as I have set up in the draft.

**Comment by bennahugo** [comment]
I will debug this tomorrow. Hopefully it can go in soonish

**Comment by bennahugo** [comment]
Ok I have it working :)

Here is an example TDL 
```ini
[turbo-sim]
dipole_model = lba_model
me.e_enable = 1
me.e_module = Siamese_OMS_pybeams_fits
me.l_module = Rotation
me.sky.tiggerskymodel = 1
me.z_module = Siamese_OMS_oms_ionosphere
model_type = use_wsrt_cos3
ms_sel.ddid_index = 0
ms_sel.field_index = 2
ms_sel.input_column = DATA
ms_sel.model_column = DATA
ms_sel.ms_channel_end = 0
ms_sel.ms_channel_start = 0
ms_sel.ms_channel_step = 1
ms_sel.ms_corr_sel = 2
ms_sel.ms_polarization = XX YY
ms_sel.msname = /home/hugo/workspace/msdir/test-data.ms
ms_sel.output_column = CORRECTED_DATA
oms_gain_models.err-gain.offset = 57847.31986097712
oms_gain_models.err-gain.scale = 3.9066805858082243
oms_gain_models.err-phase.offset = 57847.31986097712
oms_gain_models.err-phase.scale = 3.9066805858082243
oms_pointing_errors.pe_l.offset = 57847.31986097712
oms_pointing_errors.pe_l.scale = 3.9066805858082243
oms_pointing_errors.pe_m.offset = 57847.31986097712
oms_pointing_errors.pe_m.scale = 3.9066805858082243
pybeams_fits.filename_pattern = /home/hugo/workspace/msdir/stationspec.json
pybeams_fits.l_axis = px
pybeams_fits.m_axis = py
pybeams_fits.missing_is_null = 0
pybeams_fits.sky_rotation = 0
pybeams_fits.verbose_level = 1
selname = Lions_PiercePoints_modules_TID_MIM
tiggerlsm.filename = /home/hugo/workspace/msdir/sim_model.txt
```

With stationspec.json defined as
```json
{
        "lband": {
                "patterns": {
                        "cmd::default": "/home/hugo/workspace/beams/$(stype).holo.lband.2deg_$(corr)_$(reim).fits",
                        "unitybeam": "/home/hugo/workspace/beams/unity.holo.lband.2deg_$(corr)_$(reim).fits"
                },
                "define-stationtypes": {
                        "cmd::default": "mk",
                        "m000": "unitybeam",
                        "m060": "unitybeam"
                }
        }
}
```
with sky model looking like
```
#format: ra_h ra_m ra_s dec_d dec_m dec_s i freq0 spi
04 13 26.400000 -81 0 0 1 1e6 0.0
```
and the original database having a phase center as follows
```
2022-03-30 10:36:31     INFO    listobs::ms::summary    Fields: 1
2022-03-30 10:36:31     INFO    listobs::ms::summary+     ID   Code Name                RA               Decl           Epoch   SrcId      nRows
2022-03-30 10:36:31     INFO    listobs::ms::summary+     2    T    DEEP_2              04:13:26.400000 -80.00.00.00000 J2000   2         129480
```
I've done the basic checks to verify that the new implementation works with lists of beamset patterns (picking up the first in this case), since all of them have the same frequency coverages. 

The basic test is defined then as:
 - Run meqtrees with specified config, predicting a flatspectrum 1Jy source at 1 degree from the pointing / phase center of the database
 - Run fixvis with rephaseing to the location of the source to remove geometric phase effects for inspection
 ```python
CASA <25>: inp
---------> inp()
#  fixvis :: Recalculates (u, v, w) and/or changes Phase Center 
vis                 = 'test-data.ms/'   #  Name of the input visibility set.
outputvis           = 'test-data.ps.ms' #  Name of the output visibility set.
                                        #   (Can be the same as vis.)
field               =        '2'        #  Fields to operate on.   = all.
refcode             =         ''        #  reference frame to convert UVW
                                        #   coordinates to
reuse               =       True        #  base UVW calculation on the old
                                        #   values?
phasecenter         = 'J2000 4h13m26.4000s -81d00m00.00s' #  use this direction
                                        #   as phase center
distances           =         ''        #  (experimental) List of the distances
                                        #   (as quanta) of the fields selected
                                        #   by field.
datacolumn          =      'all'        #  when applying a phase center shift,
                                        #   modify visibilities only in
                                        #   this/these column(s)

 ```
This again (without sky rotation turned on) results in the three sets of lines:
~~0.3 is Ep == Eq
~~0.5 is Ep or Eq == unitybeam type and the other "mk" type
==1 is m000&m060
image
image
image
image

**Comment by bennahugo** [comment]
@richarms Please see proposed implementation to support simulation for a heterogeneous SKA MID array. This follows exactly the same pattern specification in meqtrees that we have with DDFacet/killMS

**Comment by IanHeywood** [comment]
Nothing to add other than that this is awesome.

**Comment by bennahugo** [comment]
> Nothing to add other than that this is awesome.

Yup... "your colony has reached the SKA era" :)
Now to port this into cubical and we will complete the circle...

**Comment by twillis449** [comment]
My apologies for not replying earlier to some of your previous questions. But it would appear that you've made significant progress in getting MeqTrees up and running again. So congratulations on that achievement! 

I do not recall exactly what fits_beams0 did  - but my beam fitting had to do with the simulation of focal plane arrays - take the underlying beam elements of an array and fitting/solving for appropriate beam weights so that one obtained a nice circular 'phased up' beam in any specified direction. And then do a simulated observation where all telescopes in the array would have the same simulated primary beam. But it looks like you want to simulate the SKA-MID where the MeerKAT antennas have a different size and beam compared to the coming SKA dishes - so a somewhat different problem.

**Comment by bennahugo** [comment]
Ahh ok thanks for clarifying what that class should be doing @twillis449 -- ok then I'm correct in only modifying @o-smirnov's pybeams_fits

I haven't yet gained much traction on the Qt front -- I first had to get these extensions for DDFacet/killms/cubical and Meqtrees out of the way. I will get back to that next

**Comment by bennahugo** [comment]
retest this please

**Comment by bennahugo** [comment]
Ping for @o-smirnov to review

**Review by o-smirnov — APPROVED** [review]
LGTM!

**Pull request merged**
